START TRANSACTION;

DROP TABLE IF EXISTS "employee_project";
DROP TABLE IF EXISTS "project";
DROP TABLE IF EXISTS "employee";
DROP TABLE IF EXISTS "job_title";
DROP TABLE IF EXISTS "department";

CREATE TABLE "department" (
        "department_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "name" VARCHAR(128) NOT NULL,

        CONSTRAINT "pk_department_id" PRIMARY KEY("department_id")
);

CREATE TABLE "job_title" (
        "job_title_id" INT GENERATED ALWAYS AS IDENTITY NOT NULL,
        "name" VARCHAR(32) NOT NULL,
        
        CONSTRAINT "pk_job_title_id" PRIMARY KEY("job_title_id")
);

CREATE TABLE "employee" (
        "employee_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "job_title_id" INT NOT NULL,
        "first_name" VARCHAR(64) NOT NULL,
        "last_name" VARCHAR(64) NOT NULL,
        "gender" VARCHAR(16),
        "birth_date" DATE,
        "hire_date" DATE,
        "department_id" INT NOT NULL,
        
        CONSTRAINT "pk_employee_id" PRIMARY KEY("employee_id"),
        CONSTRAINT "fk_job_title_id" FOREIGN KEY("job_title_id") REFERENCES "job_title" ("job_title_id"),
        CONSTRAINT "fk_department_id" FOREIGN KEY("department_id") REFERENCES "department" ("department_id"),
        CONSTRAINT "ck_gender" CHECK ("gender" IN ('Male', 'Female', 'Other', 'Undisclosed'))
);

CREATE TABLE "project" (
        "project_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "name" VARCHAR(128) NOT NULL,
        "start_date" TIMESTAMP NOT NULL,
        
        CONSTRAINT "pk_project_id" PRIMARY KEY("project_id")
);

CREATE TABLE "employee_project" (
        "project_id" INT NOT NULL,
        "employee_id" INT NOT NULL,
        
        CONSTRAINT "pk_project_id_employee_id" PRIMARY KEY("project_id", "employee_id"),
        CONSTRAINT "fk_project_id" FOREIGN KEY("project_id") REFERENCES "project" ("project_id"),
        CONSTRAINT "fk_employee_id" FOREIGN KEY("employee_id") REFERENCES "employee" ("employee_id")
);

-- Populate the tables with data for at least four projects, three departments, and eight employees.
INSERT INTO "project" ("name", "start_date") VALUES
                      ('Journeyman Project', '1993-01-06'),
                      ('Project Dolphin', '1999-05-09'),
                      ('Project Revolution', '2006-04-27'),
                      ('Project NX', '2012-11-18')
;

INSERT INTO "department" ("name") VALUES
                         ('Nintendo'),
                         ('Playstation'),
                         ('Xbox')
;

INSERT INTO "job_title" ("name") VALUES
                       ('President'),
                       ('Developer'),
                       ('Producer'),
                       ('Communications'),
                       ('Chairman'),
                       ('Executive VP'),
                       ('Director')
;

INSERT INTO "employee" ("job_title_id", "first_name", "last_name", "gender", "birth_date", "hire_date", "department_id") VALUES
                       ((SELECT "job_title_id" FROM "job_title" WHERE "name" = 'President'), 'Shuntaro', 'Furukawa', 'Male', '1972-01-10', '2018-06-28', (SELECT "department_id" FROM "department" WHERE "name" = 'Nintendo')),
                       ((SELECT "job_title_id" FROM "job_title" WHERE "name" = 'Developer'), 'Masahiro', 'Sakurai', 'Male', '1970-08-03', '1992-04-27', (SELECT "department_id" FROM "department" WHERE "name" = 'Nintendo')),
                       ((SELECT "job_title_id" FROM "job_title" WHERE "name" = 'Producer'), 'Shigeru', 'Miyamoto', 'Male', '1952-11-16', '1977-03-22', (SELECT "department_id" FROM "department" WHERE "name" = 'Nintendo')),
                       ((SELECT "job_title_id" FROM "job_title" WHERE "name" = 'Communications'), 'Andrew', 'House', 'Male', '1965-01-23', '1990-10-11', (SELECT "department_id" FROM "department" WHERE "name" = 'Playstation')),
                       ((SELECT "job_title_id" FROM "job_title" WHERE "name" = 'Chairman'), 'Kaz', 'Hirai', 'Male', '1960-12-22', '1992-02-15', (SELECT "department_id" FROM "department" WHERE "name" = 'Playstation')),
                       ((SELECT "job_title_id" FROM "job_title" WHERE "name" = 'Developer'), 'Adam', 'Boyes', 'Male', '1976-05-29', '1997-03-17', (SELECT "department_id" FROM "department" WHERE "name" = 'Playstation')),
                       ((SELECT "job_title_id" FROM "job_title" WHERE "name" = 'Executive VP'), 'Phil', 'Spencer', 'Male', '1968-01-12', '1988-03-12', (SELECT "department_id" FROM "department" WHERE "name" = 'Xbox')),
                       ((SELECT "job_title_id" FROM "job_title" WHERE "name" = 'Director'), 'Lawrence', 'Hyrb', 'Male', '1976-11-28', '2001-05-16', (SELECT "department_id" FROM "department" WHERE "name" = 'Xbox'))
;

-- Make sure each project has at least one employee assigned to it, and each department has at least two employees.
INSERT INTO "employee_project" ("project_id", "employee_id")
                (SELECT "project_id", "employee_id" FROM (
                        SELECT "employee_id", "project_id", ROW_NUMBER() OVER(ORDER BY "project_id", "employee_id") FROM "employee", "project"
                ) AS "tmp" WHERE "row_number"%10 IN (1,2));

COMMIT;

SELECT "project"."name" AS "project_name", "department"."name" AS "department_name", "employee_id", "first_name", "last_name", "gender", "birth_date", CAST(EXTRACT(YEAR FROM age("birth_date")) AS INT) AS "current_age", "hire_date", CAST(EXTRACT(YEAR FROM age("hire_date", "birth_date")) AS INT) AS "hire_age", CAST(EXTRACT(YEAR FROM age("hire_date")) AS INT) AS "hired_years_ago"
FROM "employee"
JOIN "department" USING("department_id")
JOIN "job_title" USING("job_title_id")
JOIN "employee_project" USING("employee_id")
JOIN "project" USING("project_id")
ORDER BY "hired_years_ago" DESC;